version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
      - REACT_APP_MAPS_API_KEY=${REACT_APP_MAPS_API_KEY}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - apollo_backend

  python-service:
    build: 
      context: ./python-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NASA_TEMPO_API_KEY=${NASA_TEMPO_API_KEY}
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - OPENAQ_API_KEY=${OPENAQ_API_KEY}
    volumes:
      - ./python-service:/app
    depends_on:
      - redis

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend

volumes:
  redis_data:
