services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:80/api
      - REACT_APP_MAPS_API_KEY=${REACT_APP_MAPS_API_KEY:-}
    volumes:
      - ./frontend:/app
      - /app/node_modules

  python-service:
    build: 
      context: ./python-service
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    environment:
      - NASA_TEMPO_API_KEY=${NASA_TEMPO_API_KEY:-}
      - WEATHER_API_KEY=${WEATHER_API_KEY:-}
      - OPENAQ_API_KEY=${OPENAQ_API_KEY:-}
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6379
    volumes:
      - ./python-service:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  redis_data: